storage:
    # File validation settings
    validation:
        # Default maximum file size (used when no specific rule limit is set)
        default_max_size: '10MB'

        # Default action for files that don't match any rules
        default_action: 'block' # Block everything by default

        # MIME type validation
        strict_mime_validation: true

        # File validation rules
        rules:
            - name: 'Allow Images'
              extensions: ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']
              max_size: '5MB'
              allow: true

            - name: 'Allow Documents'
              patterns: ['*.pdf', '*.doc', '*.docx', '*.txt', '*.csv', '*.rtf']
              mime_types: ['application/pdf', 'application/msword', 'text/*']
              max_size: '20MB'
              allow: true

            - name: 'Allow Archives'
              extensions: ['zip', 'rar', '7z', 'tar', 'gz']
              max_size: '100MB'
              allow: true

            - name: 'Allow Media'
              extensions: ['mp4', 'avi', 'mov', 'mkv', 'mp3', 'wav', 'flac']
              max_size: '200MB'
              allow: true

            - name: 'Allow Data Files'
              extensions: ['json', 'xml', 'yaml', 'yml']
              max_size: '10MB'
              allow: true

            - name: 'Allow Code Files'
              extensions: ['js', 'ts', 'py', 'go', 'java', 'cpp', 'c', 'h']
              max_size: '5MB'
              allow: true

            - name: 'Block Executables'
              extensions: ['exe', 'bat', 'cmd', 'sh', 'ps1', 'vbs', 'com', 'pif', 'scr']
              allow: false

            - name: 'Block Packages'
              extensions: ['app', 'dmg', 'deb', 'rpm']
              allow: false

    # Storage organization settings
    organization:
        # Default organization pattern: date/type/filename
        # Options: date, type
        pattern: 'date/type'

        # Date format for folder naming
        date_format: '2006-01-02'

        # Include time in date folders (creates hourly folders)
        include_time: false

        # File naming strategy
        naming:
            # Options: original, uuid, timestamp
            strategy: 'uuid'
            # Preserve original extension
            preserve_extension: true

    # Local storage settings
    storage:
        # Base upload directory
        upload_dir: './uploads'
        # Create directories if they don't exist
        create_dirs: true
